import type { Metadata } from 'next';
import './globals.css';
import NextAuthSession from './NextSession';
import Script from 'next/script';
import { Toaster } from 'react-hot-toast';
import StoreProvider from '@/components/Providers';

export const metadata: Metadata = {
  title: 'Cerita.in',
  description: 'Generated by create next app',
  icons: {
    icon: [
      { url: '/logo-ceritain-circle.svg', sizes: '32x32', type: 'image/png' },
    ],
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <Script
          src="https://kit.fontawesome.com/a076d05399.js"
          crossOrigin="anonymous"
        />
      </head>
      <StoreProvider>
        <body className="antialiased min-h-screen">
          <Toaster position="top-center" reverseOrder={false} />
          <NextAuthSession>{children}</NextAuthSession>
        </body>
      </StoreProvider>
    </html>
  );
}
