// app/layout.tsx
import type { Metadata } from 'next';
import './globals.css';
import NextAuthSession from './NextSession';

export const metadata: Metadata = {
  title: 'Cerita.in',
  description: 'Generated by create next app',
  icons: {
    icon: [
      { url: '/logo-ceritain-circle.svg', sizes: '32x32', type: 'image/png' },
    ],
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="antialiased min-h-screen">
        <NextAuthSession>{children}</NextAuthSession>
      </body>
    </html>
  );
}
