import type { Metadata } from 'next';
import './globals.css';
import NextAuthSession from './NextSession';
import { Toaster } from 'react-hot-toast';
import StoreProvider from '@/components/Providers';

export const metadata: Metadata = {
  title: 'Cerita.in',
  description: 'Generated by create next app',
  icons: {
    icon: [
      { url: '/logo-ceritain-circle.svg', sizes: '32x32', type: 'image/png' },
    ],
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <StoreProvider>
        <body className="antialiased min-h-screen">
          <Toaster position="top-center" reverseOrder={false} />
          <NextAuthSession>{children}</NextAuthSession>
        </body>
      </StoreProvider>
    </html>
  );
}
